# Generated by Django 2.0.5 on 2018-05-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('npi', models.PositiveIntegerField(help_text='A number between 1000000000 and 19999999999', primary_key=True, serialize=False)),
                ('board_cert', models.BooleanField(default=False, help_text='Whether or not the doctor is board certified')),
                ('age', models.PositiveSmallIntegerField(help_text='The doctors age')),
                ('rating', models.PositiveSmallIntegerField(default=4, help_text='A rating from 1 to 5')),
                ('language', models.CharField(default='English', help_text='The doctors most proficient language', max_length=256)),
                ('location', models.CharField(help_text='The primary office location of this doctor', max_length=256)),
            ],
        ),
    ]
