# Generated by Django 2.0.5 on 2018-05-22 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addentry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='npi',
            field=models.PositiveIntegerField(help_text='A number between 1000000000 and 1999999999', primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(1999999999), django.core.validators.MinValueValidator(1000000000)]),
        ),
        migrations.AlterField(
            model_name='physician',
            name='rating',
            field=models.PositiveSmallIntegerField(default=4, help_text='A rating from 1 to 5', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
